package com.example.demo.entity;

import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.time
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.storename
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    private String storename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.storenumber
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    private Integer storenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.money
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.uid
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sid
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    private Integer sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.time
     *
     * @return the value of orders.time
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.time
     *
     * @param time the value for orders.time
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.storename
     *
     * @return the value of orders.storename
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public String getStorename() {
        return storename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.storename
     *
     * @param storename the value for orders.storename
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public void setStorename(String storename) {
        this.storename = storename == null ? null : storename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.storenumber
     *
     * @return the value of orders.storenumber
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public Integer getStorenumber() {
        return storenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.storenumber
     *
     * @param storenumber the value for orders.storenumber
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public void setStorenumber(Integer storenumber) {
        this.storenumber = storenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.money
     *
     * @return the value of orders.money
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.money
     *
     * @param money the value for orders.money
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.uid
     *
     * @return the value of orders.uid
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.uid
     *
     * @param uid the value for orders.uid
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sid
     *
     * @return the value of orders.sid
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sid
     *
     * @param sid the value for orders.sid
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }
}