package com.example.demo.entity;

public class Shopowner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopowner.id
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopowner.phone
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopowner.password
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopowner.flag
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    private String flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopowner.id
     *
     * @return the value of shopowner.id
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopowner.id
     *
     * @param id the value for shopowner.id
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopowner.phone
     *
     * @return the value of shopowner.phone
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopowner.phone
     *
     * @param phone the value for shopowner.phone
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopowner.password
     *
     * @return the value of shopowner.password
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopowner.password
     *
     * @param password the value for shopowner.password
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopowner.flag
     *
     * @return the value of shopowner.flag
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopowner.flag
     *
     * @param flag the value for shopowner.flag
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }
}