package com.example.demo.mapper;

import com.example.demo.entity.Comm;
import com.example.demo.entity.CommExample;
import com.example.demo.entity.Orders;

import java.util.List;

public interface CommMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    int insert(Comm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    int insertSelective(Comm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    List<Comm> selectByExample(CommExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    Comm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    int updateByPrimaryKeySelective(Comm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    int updateByPrimaryKey(Comm record);
    
    List<Orders> getByUid(int uid);

    Comm Login(String phone,String password);
}