package com.example.demo.mapper;

import com.example.demo.entity.Orders;
import com.example.demo.entity.Sale;
import com.example.demo.entity.Shopowner;
import com.example.demo.entity.ShopownerExample;
import java.util.List;

public interface ShopownerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopowner
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopowner
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    int insert(Shopowner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopowner
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    int insertSelective(Shopowner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopowner
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    List<Shopowner> selectByExample(ShopownerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopowner
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    Shopowner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopowner
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    int updateByPrimaryKeySelective(Shopowner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopowner
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    int updateByPrimaryKey(Shopowner record);

    List<Sale> getBySid(int sid);      //查询某一餐厅 当年每月的销售量
}