package com.example.demo.mapper;

import com.example.demo.entity.Store;
import com.example.demo.entity.StoreExample;
import java.util.List;

public interface StoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    int insert(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    int insertSelective(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    List<Store> selectByExample(StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    Store selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    int updateByPrimaryKeySelective(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Sun Aug 25 09:40:05 CST 2019
     */
    int updateByPrimaryKey(Store record);
    
    List<Store> getByAll();                          //为了匹配搜索引擎的 索引而建
    
    List<Store> getByArea(String area);               //搜索引擎功能 待改进
    
    List<Store> getByCity(String city);               //搜索引擎功能 待改进

    List<Store> getByStorename(String storename);               //搜索引擎功能 待改进
    
    List<Store> getStoreById(int id);                           //根据搜索引擎模糊匹配 找到具体的商店
    
    int updateClickByid(int id,int click);                      //根据搜索次数 更新 点击量
    
    List<Store> getByClick();                          //更具点击量 列出热搜索的餐厅 
    
    List<Store> getByCityAndArea(String city,String area);   //防止用户输入 空格及市区值同步输入
    
}